config/routes.rb
Rails.application.routes.draw do
  resources :employees
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "employees#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :employees
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 include Pagy::Backend

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[ show edit update destroy ]

  # GET /employees or /employees.json
  def index
    if current_user
      @employees = current_user&.employees
      if params[:search].present?
        @employees = @employees.where("name OR email LIKE ?", "%#{params[:search]}%") 
      end
      @pagy, @employees = pagy(@employees, items: 7)
    end
  end

  # GET /employees/1 or /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees or /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to employee_url(@employee), notice: "Employee was successfully created." }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employee_url(@employee), notice: "Employee was successfully updated." }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url, notice: "Employee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:name, :email, :bio, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
 include Pagy::Frontend
end

app/helpers/employees_helper.rb
module EmployeesHelper
 def avatar_url(employee)
  if employee.present?
   gravatar_id = Digest::MD5::hexdigest(employee).downcase
   "http://gravatar.com/avatar/#{gravatar_id}.png"
  else 
   "http://gravatar.com/avatar/images/guest.png" 
 end
end
end

app/views/employees/_employee.html.erb
<tr>
  <td ><%= image_tag avatar_url(employee.email) %></td>
  <td class="text-sm md:text-md"><%= employee.name %></td>
  <td class="text-sm md:text-lg"><%= employee.email %></td>
  <td class="text-sm "><%= employee.bio %></td>

  <% if action_name != "show" %>
    <td><%= link_to "Show this employee", employee, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block text-sm h-12 ring-2 ring-blue-600" %> </td>
    <td><%= link_to fa_icon('gear', text: "edit"), edit_employee_path(employee), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block text-sm h-12 ring-2 ring-blue-600" %> </td>
  <% end %>
</tr>




 

app/views/employees/_form.html.erb
<%= form_with(model: employee, class: "contents") do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :email %>
    <%= form.text_field :email, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :bio %>
    <%= form.text_area :bio, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing employee</h1>

  <%= render "form", employee: @employee %>

  <%= link_to "Show this employee", @employee, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to employees", employees_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/employees/index.html.erb
<% if user_signed_in? %>
  <div class="w-full">
    <% if notice.present? %>
      <p class="py-2 px-2 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <div class="flex justify-between">
      <h1 class="font-bold text-4xl">Employees</h1>
      <%= link_to 'Add employee', new_employee_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    </div>
    
    <%== pagy_nav(@pagy)%>
     <%= form_tag(employees_path, method: :get) do %>
     <%= text_field_tag :search, params[:search], placeholder: "Search by name or email", class: "w-full rounded-lg py-3 px-5 bg-gray-100 font-medium mt-5" %>
     <%= submit_tag("Search", class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium") %>
     <% end %>

    
    <table id="employees" class="table-auto w-full mt-5">
      <thead>
        <tr class="bg-gray-200">
          <th>Image</th>
          <th>Name: </th>
          <th>Email: </th>
          <th>Bio: </th>  
          <th>Show </th>  
          <th>Edit </th>  
        </tr>
      </thead>
      <%= render @employees %>
    </table>
  </div>

<% else %>
  <div class="w-full flex flex-col items-center ">
    <h1 class="mt-10 font-bold text-4xl">Employees</h1>
    <p class="mt-10 text-2xl">Please login to view the employee directory</p>
    <%= link_to 'Login' , new_user_session_path,
      class: "rounded-lg py-3 px-5 bg-blue-600 text-white font-medium w-1/3 text-center text-lg mt-5" 
    %>
  </div>
<% end %>

app/views/employees/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New employee</h1>

  <%= render "form", employee: @employee %>

  <%= link_to 'Back to employees', employees_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/employees/show.html.erb
<div class="mx-auto">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
 </div>
</div>

  <div class="w-full flex justify-center">
   <%= image_tag avatar_url(@employee.email), class: "w-48 flex-none bg-cover rounded-t lg:rounded-t-none lg:rounded-l text-center overflow-hidden" %>
  <div class="border-r border-b border-l border-gray-400 lg:border-l-0 lg:border-t lg:border-gray-400 bg-white rounded-b lg:rounded-b-none lg:rounded-r p-4 flex flex-col justify-between leading-normal">
    <div >
      <p class="text-gray-900 font-bold text-xl"><%= @employee.name %></div>
      <p class="text-gray-700 text-base">Email: <%= @employee.email %></p>
      <p class="text-gray-700 text-base">Bio: <%= @employee.bio %></p>
    </div>
  </div>
  <div class="flex w-full flex-col items-center mt-2">
  <%= link_to 'Edit', edit_employee_path(@employee), class: "text-center rounded-lg py-3 px-5 bg-gray-100 font-medium w-52" %>
   <%= button_to 'Destroy this employee', employee_path(@employee), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
  <%= link_to 'Back', employees_path, class: "text-center mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium w-52" %>
</div>
 
</div>

app/views/layouts/_header.html.erb
<header class="flex justify-center items-center">
 <div class="relative w-full">
  <%= image_tag("images2.jpeg", class: "w-full h-72 bg-cover bg-center ") %>
  <h1 class="absolute top-1/3 left-1/2 -translate-x-1/2 -translate-y-1/2 mt-10 font-bold text-6xl text-white ">Employee Directory</h1>
 </div>
</header> 

app/views/layouts/_navbar.html.erb
<nav class="flex h-14 bg-slate-600 items-center">
    <div class="container mx-auto px-4">
      <div class="flex justify-between">
        <div class="flex space-x-4">
                <!-- Logo -->
          <div>
            <%= link_to "Employee Directory", root_path, class: "text-white text-xl font-bold" %>
          </div>
            
        </div>
         <div class="hidden md:flex items-center space-x-1">
                <%= link_to "Employees", employees_path, class: "text-white hover:bg-slate-700 px-3 py-2 rounded" %>

                <% if user_signed_in? %>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "text-white hover:bg-slate-700 px-3 py-2 rounded" %>
                <% else %>
                <%= link_to "Login", new_user_session_path, class: "text-white hover:bg-slate-700 px-3 py-2 rounded" %>
                <% end %>
            </div>
        </div>
    </div>

    <!--  mobile menu -->
    <div class="md:hidden">
        <button class="mobile-menu-button flex items-center px-3 py-2 border rounded text-slate-200 border-slate-400 hover:text-white hover:border-white mx-4">
            <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
        </button>

        <div class="mobile-menu hidden">
            <ul>
                <li><%= link_to "Employees", employees_path, class: "block text-white hover:bg-slate-700 px-3 py-2 rounded" %></li>
                <% if user_signed_in? %>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete, class: "block text-white hover:bg-slate-700 px-3 py-2 rounded" %></li>
                <% else %>
                <li><%= link_to "Login", new_user_session_path, class: "block text-white hover:bg-slate-700 px-3 py-2 rounded" %></li>
                <% end %>
            </ul>
    </div>   

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmployeeDirectory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= render 'magic_test/support' if Rails.env.test? %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= render "layouts/header" %>
    <main class="container mx-auto mt-28 px-5">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
    </main>
  </body>
</html>